AzRBlog.Web/Areas/Admin/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AzRBlog.Web.Areas.Admin.Controllers
{
    public class TagController : Controller
    {
        // GET: Admin/Tag
        public ActionResult Index()
        {
            return View();
        }
    }
}

AzRBlog.Web/Controllers/BlogController.cs
using System.Web.Mvc;

namespace AzRBlog.Web.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }
    }
}

AzRBlog.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AzRBlog.Web.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

AzRBlog.Web/Controllers/UserAuthController.cs
using AzRBlog.Entities.Models;
using AzRBlog.Web.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AzRBlog.Web.Controllers
{
    [Authorize]
    public class UserAuthController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public UserAuthController()
        {
        }

        public UserAuthController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        //
        // GET: /Account/VerifyCode
        [AllowAnonymous]
        public async Task<ActionResult> VerifyCode(string provider, string returnUrl, bool rememberMe)
        {
            // Require that the user has already logged in via username/password or external login
            if (!await SignInManager.HasBeenVerifiedAsync())
            {
                return View("Error");
            }
            return View(new VerifyCodeViewModel { Provider = provider, ReturnUrl = returnUrl, RememberMe = rememberMe });
        }

        //
        // POST: /Account/VerifyCode
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyCode(VerifyCodeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // The following code protects for brute force attacks against the two factor codes. 
            // If a user enters incorrect codes for a specified amount of time then the user account 
            // will be locked out for a specified amount of time. 
            // You can configure the account lockout settings in IdentityConfig
            var result = await SignInManager.TwoFactorSignInAsync(model.Provider, model.Code, isPersistent: model.RememberMe, rememberBrowser: model.RememberBrowser);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(model.ReturnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid code.");
                    return View(model);
            }
        }

        //
        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Register()
        {
            var model = new RegisterViewModel
            {
                IsAgreeTermAndCondition = true
            };
            return View(model);
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = model.Email,
                    Email = model.Email,
                    PhoneNumber = model.PhoneNumber,
                    Profile = new UserProfile
                    {
                        Name = model.FullName,
                        Mobile = model.PhoneNumber,

                    }
                };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);

                    // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ConfirmEmail
        [AllowAnonymous]
        public async Task<ActionResult> ConfirmEmail(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return View("Error");
            }
            var result = await UserManager.ConfirmEmailAsync(userId, code);
            return View(result.Succeeded ? "ConfirmEmail" : "Error");
        }

        //
        // GET: /Account/ForgotPassword
        [AllowAnonymous]
        public ActionResult ForgotPassword()
        {
            return View();
        }

        //
        // POST: /Account/ForgotPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByNameAsync(model.Email);
                if (user == null || !(await UserManager.IsEmailConfirmedAsync(user.Id)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return View("ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                // Send an email with this link
                // string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
                // var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);		
                // await UserManager.SendEmailAsync(user.Id, "Reset Password", "Please reset your password by clicking <a href=\"" + callbackUrl + "\">here</a>");
                // return RedirectToAction("ForgotPasswordConfirmation", "Account");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ForgotPasswordConfirmation
        [AllowAnonymous]
        public ActionResult ForgotPasswordConfirmation()
        {
            return View();
        }

        //
        // GET: /Account/ResetPassword
        [AllowAnonymous]
        public ActionResult ResetPassword(string code)
        {
            return code == null ? View("Error") : View();
        }

        //
        // POST: /Account/ResetPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ResetPassword(ResetPasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await UserManager.FindByNameAsync(model.Email);
            if (user == null)
            {
                // Don't reveal that the user does not exist
                return RedirectToAction("ResetPasswordConfirmation", "Account");
            }
            var result = await UserManager.ResetPasswordAsync(user.Id, model.Code, model.Password);
            if (result.Succeeded)
            {
                return RedirectToAction("ResetPasswordConfirmation", "Account");
            }

AzRBlog.Web/Views/Shared/NotFound.cshtml
<div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
    <div class="row flex-grow">
        <div class="col-lg-7 mx-auto text-white">
            <div class="row align-items-center d-flex flex-row">
                <div class="col-lg-6 text-lg-right pr-lg-4">
                    <h1 class="display-1 mb-0">404</h1>
                </div>
                <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                    <h2>SORRY!</h2>
                    <h3 class="font-weight-light">The page you’re looking for was not found.</h3>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-12 text-center mt-xl-2">
                    <a class="text-white font-weight-medium" href="@Url.Action("Index","Home",new{area=""})">Back to home</a>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-12 mt-xl-2">
                    <p class="text-white font-weight-medium text-center">Copyright &copy; 2018 All rights reserved.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- content-wrapper ends -->

AzRBlog.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AzR Blog</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="/Themes/Admin/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/Themes/Admin/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="/Themes/Admin/vendors/css/vendor.bundle.addons.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="/Themes/Admin/css/style.css">
    <!-- endinject -->
    @*<link rel="shortcut icon" href="/favicon.png" />*@

    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
</head>

<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
                <a class="navbar-brand brand-logo" href="@Url.Action("Index","Dashboard",new{area=""})">
                    @*<img src="/" alt="logo" />*@
                    AzR BLOG
                </a>
                <a class="navbar-brand brand-logo-mini" href="@Url.Action("Index","Dashboard",new{area=""})">
                    @*<img src="/" alt="logo" />*@
                    AzR
                </a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center">
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item dropdown">
                        @{Html.RenderPartial("_MessageDropdown");}
                    </li>
                    <li class="nav-item dropdown">
                        @{Html.RenderPartial("_NotificationDropdown");}
                    </li>
                    <li class="nav-item dropdown d-none d-xl-inline-block">
                        @{Html.RenderPartial("_UserDropdown");}
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
           @{Html.RenderPartial("_Sidebar");}
            <!-- partial -->
            <div class="main-panel">
                <div id="mainContainer" class="main-container">
                    @RenderBody()
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="container-fluid clearfix">
                        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
                            Copyright ©
                            <script>document.write(new Date().getFullYear());</script>
                            <a href="https://stackoverflow.com/users/3557266/ashiquzzaman" target="_blank">AzR</a>. All rights reserved.
                        </span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">
                            Developed by <i class="mdi mdi-heart text-danger"></i> AzR

                        </span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    @using (Html.BeginForm("LogOff", "UserAuth", new { area=""}, FormMethod.Post,new { id = "logoutForm" }))
    {@Html.AntiForgeryToken()}
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="/Themes/Admin/vendors/js/vendor.bundle.base.js"></script>
    <script src="/Themes/Admin/vendors/js/vendor.bundle.addons.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="/Themes/Admin/js/off-canvas.js"></script>
    <script src="/Themes/Admin/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="/Themes/Admin/js/dashboard.js"></script>
    <!-- End custom js for this page-->

    
     @*@Scripts.Render("~/bundles/jquery")
     @Scripts.Render("~/bundles/bootstrap")*@

    @RenderSection("scripts", required: false)
</body>

</html>

AzRBlog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Ruft Blog</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500|Rubik:500" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="/Themes/Blog/css/linearicons.css">
    <link rel="stylesheet" href="/Themes/Blog/css/font-awesome.min.css">
    <link rel="stylesheet" href="/Themes/Blog/css/bootstrap.css">
    <link rel="stylesheet" href="/Themes/Blog/css/magnific-popup.css">
    <link rel="stylesheet" href="/Themes/Blog/css/nice-select.css">
    <link rel="stylesheet" href="/Themes/Blog/css/animate.min.css">
    <link rel="stylesheet" href="/Themes/Blog/css/owl.carousel.css">
    <link rel="stylesheet" href="/Themes/Blog/css/main.css">
</head>

<body>
    <!--================ Start header Top Area =================-->
    <section class="header-top">
        <div class="container box_1170">
            <div class="row align-items-center justify-content-between">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <a href="@Url.Action("Index","Home",new{area=""})" class="logo">
                        @*<img src="/Themes/Blog/img/logo.png" alt="">*@
                        <h1 style="color: #25aec5;">AzR BLOG</h1>
                    </a>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 search-trigger">
                    <a href="#" class="search">
                        <i class="lnr lnr-magnifier" id="search"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <!--================ End header top Area =================-->
    <!-- Start header Area -->
    <header id="header">
        <div class="container box_1170 main-menu">
            <div class="row align-items-center justify-content-center d-flex">
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li class="menu-active">
                            <a href="@Url.Action("Index","Home",new{area=""})">Home</a>
                        </li>
                        <li><a href="@Url.Action("Index","Blog",new{area=""})">Category</a></li>
                        <li><a href="@Url.Action("Index","Blog",new{area=""})">Archive</a></li>


                        <li><a href="@Url.Action("Contact","Home",new{area=""})">Contact</a></li>

                        @if (!Request.IsAuthenticated)
                        {
                            <li><a href="@Url.Action("Register","UserAuth",new{area=""})">Register</a></li>
                            <li><a href="@Url.Action("Login","UserAuth",new{area=""})">Login</a></li>
                        }
                        else
                        {
                            <li class="menu-has-children">
                                <a href="">My Account</a>
                                <ul>
                                    <li>
                                        <a href="@Url.Action("Index","Dashboard",new{area=""})">
                                            Dashboard
                                        </a>
                                    </li>
                                    <li>
                                        <a href="javascript:document.getElementById('logoutForm').submit()">
                                            Sign Out
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }

                    </ul>
                </nav>
            </div>
        </div>

        <div class="search_input" id="search_input_box">
            <div class="container box_1170">
                <form class="d-flex justify-content-between">
                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                    <span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
    <!-- End header Area -->


    @RenderBody()

    <!-- start footer Area -->
    <footer class="footer-area section-gap">
        <div class="container box_1170">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6 class="footer_title">About Us</h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
                            magna aliqua.
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6 class="footer_title">Newsletter</h6>
                        <p>Stay updated with our latest trends</p>
                        <div id="mc_embed_signup">
                            <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                  method="get" class="subscribe_form relative">
                                <div class="input-group d-flex flex-row">
                                    <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '"
                                           required="" type="email">
                                    <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>
                                </div>
                                <div class="mt-10 info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="single-footer-widget instafeed">
                        <h6 class="footer_title">Instagram Feed</h6>
                        <ul class="list instafeed d-flex flex-wrap">
                            <li><img src="/Themes/Blog/img/i1.jpg" alt=""></li>
                            <li><img src="/Themes/Blog/img/i2.jpg" alt=""></li>
                            <li><img src="/Themes/Blog/img/i3.jpg" alt=""></li>
                            <li><img src="/Themes/Blog/img/i4.jpg" alt=""></li>
                            <li><img src="/Themes/Blog/img/i5.jpg" alt=""></li>
                            <li><img src="/Themes/Blog/img/i6.jpg" alt=""></li>
                            <li><img src="/Themes/Blog/img/i7.jpg" alt=""></li>
                            <li><img src="/Themes/Blog/img/i8.jpg" alt=""></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="single-footer-widget f_social_wd">
                        <h6 class="footer_title">Follow Us</h6>
                        <p>Let us be social</p>
                        <div class="f_social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row footer-bottom d-flex justify-content-between align-items-center">
                <p class="col-lg-12 footer-text text-center">
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved 
                    <i class="fa fa-heart-o" aria-hidden="true"></i> by 
                    <a href="https://stackoverflow.com/users/3557266/ashiquzzaman" target="_blank">AzR</a>
                </p>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->
@using (Html.BeginForm("LogOff", "UserAuth", new { area = "" }, FormMethod.Post, new { id = "logoutForm" })){@Html.AntiForgeryToken()}

    <script src="/Themes/Blog/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="/Themes/Blog/js/vendor/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="/Themes/Blog/js/easing.min.js"></script>
    <script src="/Themes/Blog/js/hoverIntent.js"></script>
    <script src="/Themes/Blog/js/superfish.min.js"></script>
    <script src="/Themes/Blog/js/jquery.ajaxchimp.min.js"></script>
    <script src="/Themes/Blog/js/jquery.magnific-popup.min.js"></script>
    <script src="/Themes/Blog/js/owl.carousel.min.js"></script>
    <script src="/Themes/Blog/js/jquery.tabs.min.js"></script>
    <script src="/Themes/Blog/js/jquery.nice-select.min.js"></script>
    <script src="/Themes/Blog/js/waypoints.min.js"></script>
    <script src="/Themes/Blog/js/mail-script.js"></script>
    <script src="/Themes/Blog/js/main.js"></script>


    @RenderSection("scripts", required: false)
</body>

</html>

AzRBlog.Web/Views/Shared/_Sidebar.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <div class="nav-link">
                <div class="user-wrapper">
                    <div class="profile-image">
                        <img src="/Themes/Admin/images/faces/face1.jpg" alt="profile image">
                    </div>
                    <div class="text-wrapper">
                        <p class="profile-name">AzR</p>
                        <div>
                            <small class="designation text-muted">Administrator</small>
                            <span class="status-indicator online"></span>
                        </div>
                    </div>
                </div>
                <button class="btn btn-success btn-block">
                    New Post
                    <i class="mdi mdi-plus"></i>
                </button>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index","Dashboard",new{area=""})">
                <i class="menu-icon mdi mdi-television"></i>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index","Post",new{area="Admin"})">
                <i class="menu-icon mdi mdi-backup-restore"></i>
                <span class="menu-title">Post</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index","Tag",new{area="Admin"})">
                <i class="menu-icon mdi mdi-chart-line"></i>
                <span class="menu-title">Tag</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index","Category",new{area="Admin"})">
                <i class="menu-icon mdi mdi-table"></i>
                <span class="menu-title">Category</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index","Report",new{area="Admin"})">
                <i class="menu-icon mdi mdi-elevation-rise"></i>
                <span class="menu-title">Report</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index","User",new{area="Admin"})">
                <i class="menu-icon mdi mdi-bio"></i>
                <span class="menu-title">User</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
                <i class="menu-icon mdi mdi-restart"></i>
                <span class="menu-title">Settings</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="auth">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Role",new{area="Admin"})"> Role </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Country",new{area="Admin"})"> Country </a>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</nav>